# Site settings
title: huxiangyu - Desenvolvedor Web
description: "Um blog sobre desenvolvimento web"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://huxiangyu.github.io" #http://localhost:3000

# User settings
username: huxiangyu
user_title: huxiangyu - FrontEnd
email: huxiangyu@mail.com
twitter_username: huxxyu
github_username:  huxiangyu
gplus_username:  huxxyu
disqus_username: huxiangyu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: meus posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: sobre mim
    url: /about
# projects in header index
projects:
  - name: NetSpeed
    url: https://github.com/huxiangyu/NetSpeed
  - name: fonts
    url: https://github.com/huxiangyu/fonts
  - name: oh-my-zsh
    url: https://github.com/huxiangyu/oh-my-zsh
  - name: hosts
    url: https://github.com/huxiangyu/hosts
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
